# Generated by Django 5.2.5 on 2026-04-02 16:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_type', models.CharField(max_length=100)),
                ('job_id', models.CharField(max_length=64, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.IntegerField(default=5)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('max_retries', models.IntegerField(default=3)),
                ('retry_count', models.IntegerField(default=0)),
                ('retry_delay_seconds', models.IntegerField(default=60)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-priority', 'scheduled_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='jobs_job_status_51252e_idx'), models.Index(fields=['job_type', 'status'], name='jobs_job_job_typ_3f135c_idx')],
            },
        ),
    ]
