# Generated by Django 5.2.5 on 2026-04-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', '-priority', 'scheduled_at'], name='jobs_job_status_0ebd7d_idx'),
        ),
    ]
