# Generated by Django 5.2.5 on 2026-04-02 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_name', models.CharField(max_length=140)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('archived', 'Archived')], default='new', max_length=20)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to='cms.page')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='core.site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('fields', models.JSONField(blank=True, default=list)),
                ('submit_button_text', models.CharField(default='Submit', max_length=60)),
                ('success_message', models.TextField(default='Thank you for your submission!')),
                ('redirect_url', models.URLField(blank=True, max_length=500)),
                ('notify_emails', models.JSONField(blank=True, default=list)),
                ('enable_captcha', models.BooleanField(default=False)),
                ('honeypot_field', models.CharField(default='website', max_length=60)),
                ('form_class', models.CharField(blank=True, max_length=255)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='core.site')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('site', 'slug'), name='forms_unique_site_form_slug')],
            },
        ),
    ]
