# Generated by Django 5.2.5 on 2026-04-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_renderer_contract_and_block_template_metadata'),
        ('core', '0001_initial'),
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['site', 'form_name', '-created_at'], name='forms_forms_site_id_f04616_idx'),
        ),
    ]
