# Generated by Django 6.0.3 on 2026-04-19 09:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def _unique_account_email(UserAccount, user, seen_emails: set[str]) -> str:
    base = (getattr(user, "email", "") or "").strip().lower()
    if not base:
        base = f"user-{user.pk}@local.invalid"
    local, _, domain = base.partition("@")
    local = local or f"user-{user.pk}"
    domain = domain or "local.invalid"
    candidate = f"{local}@{domain}"
    suffix = 2
    while candidate in seen_emails or UserAccount.objects.exclude(user_id=user.pk).filter(email=candidate).exists():
        candidate = f"{local}+{suffix}@{domain}"
        suffix += 1
    seen_emails.add(candidate)
    return candidate


def seed_identity_and_rbac(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserAccount = apps.get_model("core", "UserAccount")
    UserSecurityState = apps.get_model("core", "UserSecurityState")
    Workspace = apps.get_model("core", "Workspace")
    WorkspaceMembership = apps.get_model("core", "WorkspaceMembership")
    Site = apps.get_model("core", "Site")
    SiteMembership = apps.get_model("core", "SiteMembership")
    RBACPermission = apps.get_model("core", "RBACPermission")
    RBACRole = apps.get_model("core", "RBACRole")
    RBACRolePermission = apps.get_model("core", "RBACRolePermission")

    now = django.utils.timezone.now()
    seen_emails = set(UserAccount.objects.values_list("email", flat=True))

    for user in User.objects.all().iterator():
        account_email = _unique_account_email(UserAccount, user, seen_emails)
        account_defaults = {
            "email": account_email,
            "display_name": ((getattr(user, "first_name", "") or "").strip() or getattr(user, "username", ""))[:160],
            "status": "active" if getattr(user, "is_active", True) else "suspended",
        }
        account, created = UserAccount.objects.get_or_create(user_id=user.pk, defaults=account_defaults)
        if not created:
            updates = []
            normalized_email = (account.email or "").strip().lower()
            if not normalized_email:
                normalized_email = account_email
            if normalized_email != account.email:
                account.email = normalized_email
                updates.append("email")
            if not account.display_name:
                account.display_name = account_defaults["display_name"]
                updates.append("display_name")
            expected_status = "active" if getattr(user, "is_active", True) else "suspended"
            if account.status != expected_status and account.status in {"", None}:
                account.status = expected_status
                updates.append("status")
            if updates:
                account.save(update_fields=[*updates, "updated_at"])

        UserSecurityState.objects.get_or_create(user_id=user.pk)

    for workspace in Workspace.objects.exclude(owner_id__isnull=True).iterator():
        WorkspaceMembership.objects.get_or_create(
            workspace_id=workspace.pk,
            user_id=workspace.owner_id,
            defaults={
                "role": "owner",
                "status": "active",
                "invited_by_id": workspace.owner_id,
                "accepted_at": workspace.created_at or now,
            },
        )

    for site in Site.objects.exclude(workspace_id__isnull=True).select_related("workspace").iterator():
        owner_id = getattr(site.workspace, "owner_id", None)
        if owner_id is None:
            continue
        SiteMembership.objects.get_or_create(
            site_id=site.pk,
            user_id=owner_id,
            defaults={
                "role": "site_owner",
                "status": "active",
                "granted_by_id": owner_id,
                "accepted_at": site.created_at or now,
            },
        )

    permissions = [
        ("platform.impersonate", "platform", "Impersonate users"),
        ("platform.manage_users", "platform", "Manage platform users"),
        ("platform.manage_workspaces", "platform", "Manage platform workspaces"),
        ("platform.read_audit", "platform", "Read security audit logs"),
        ("workspace.view", "workspace", "View workspace"),
        ("workspace.edit", "workspace", "Edit workspace content/settings"),
        ("workspace.manage_members", "workspace", "Manage workspace memberships"),
        ("workspace.manage_billing", "workspace", "Manage workspace billing"),
        ("workspace.manage_sites", "workspace", "Manage workspace sites"),
        ("workspace.support", "workspace", "Support workspace users"),
        ("site.view", "site", "View site"),
        ("site.edit", "site", "Edit site"),
        ("site.manage", "site", "Manage site membership/configuration"),
        ("site.analytics", "site", "View site analytics"),
        ("site.billing", "site", "Manage site billing"),
    ]
    roles = [
        ("platform.super_admin", "Platform Super Admin", "platform", "Full platform administration"),
        ("workspace.owner", "Workspace Owner", "workspace", "Own and administer workspace"),
        ("workspace.admin", "Workspace Admin", "workspace", "Administer workspace"),
        ("workspace.editor", "Workspace Editor", "workspace", "Edit workspace content"),
        ("workspace.author", "Workspace Author", "workspace", "Author workspace content"),
        ("workspace.analyst", "Workspace Analyst", "workspace", "Read analytics"),
        ("workspace.support", "Workspace Support", "workspace", "Support operations"),
        ("workspace.billing_manager", "Workspace Billing Manager", "workspace", "Manage billing"),
        ("workspace.viewer", "Workspace Viewer", "workspace", "Read-only access"),
        ("site.site_owner", "Site Owner", "site", "Own and administer site"),
        ("site.editor", "Site Editor", "site", "Edit site content"),
        ("site.author", "Site Author", "site", "Author site content"),
        ("site.analyst", "Site Analyst", "site", "Read site analytics"),
        ("site.support", "Site Support", "site", "Support site operations"),
        ("site.billing_manager", "Site Billing Manager", "site", "Manage site billing"),
        ("site.viewer", "Site Viewer", "site", "Read-only access"),
    ]
    role_permission_codes = {
        "platform.super_admin": {
            "platform.impersonate",
            "platform.manage_users",
            "platform.manage_workspaces",
            "platform.read_audit",
        },
        "workspace.owner": {
            "workspace.view",
            "workspace.edit",
            "workspace.manage_members",
            "workspace.manage_billing",
            "workspace.manage_sites",
            "workspace.support",
        },
        "workspace.admin": {
            "workspace.view",
            "workspace.edit",
            "workspace.manage_members",
            "workspace.manage_billing",
            "workspace.manage_sites",
        },
        "workspace.editor": {"workspace.view", "workspace.edit"},
        "workspace.author": {"workspace.view", "workspace.edit"},
        "workspace.analyst": {"workspace.view"},
        "workspace.support": {"workspace.view", "workspace.support", "workspace.manage_members"},
        "workspace.billing_manager": {"workspace.view", "workspace.manage_billing"},
        "workspace.viewer": {"workspace.view"},
        "site.site_owner": {"site.view", "site.edit", "site.manage", "site.analytics", "site.billing"},
        "site.editor": {"site.view", "site.edit", "site.analytics"},
        "site.author": {"site.view", "site.edit", "site.analytics"},
        "site.analyst": {"site.view", "site.analytics"},
        "site.support": {"site.view", "site.manage"},
        "site.billing_manager": {"site.view", "site.edit", "site.billing"},
        "site.viewer": {"site.view"},
    }

    permission_map = {}
    for code, scope, description in permissions:
        permission, _ = RBACPermission.objects.get_or_create(
            code=code,
            defaults={"scope": scope, "description": description, "metadata": {}},
        )
        if permission.scope != scope or permission.description != description:
            permission.scope = scope
            permission.description = description
            permission.save(update_fields=["scope", "description", "updated_at"])
        permission_map[code] = permission

    role_map = {}
    for code, label, scope, description in roles:
        role, _ = RBACRole.objects.get_or_create(
            code=code,
            defaults={
                "label": label,
                "scope": scope,
                "description": description,
                "is_system": True,
                "metadata": {},
            },
        )
        updates = []
        if role.label != label:
            role.label = label
            updates.append("label")
        if role.scope != scope:
            role.scope = scope
            updates.append("scope")
        if role.description != description:
            role.description = description
            updates.append("description")
        if role.is_system is not True:
            role.is_system = True
            updates.append("is_system")
        if updates:
            role.save(update_fields=[*updates, "updated_at"])
        role_map[code] = role

    for role_code, permission_codes in role_permission_codes.items():
        role = role_map.get(role_code)
        if role is None:
            continue
        for permission_code in permission_codes:
            permission = permission_map.get(permission_code)
            if permission is None:
                continue
            RBACRolePermission.objects.get_or_create(role_id=role.pk, permission_id=permission.pk)


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_usersecuritystate_personalapikey_securityauditlog_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RBACPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=120, unique=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("platform", "Platform"),
                            ("workspace", "Workspace"),
                            ("site", "Site"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=280)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["scope", "code"],
            },
        ),
        migrations.CreateModel(
            name="RBACRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80, unique=True)),
                ("label", models.CharField(max_length=140)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("platform", "Platform"),
                            ("workspace", "Workspace"),
                            ("site", "Site"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=280)),
                ("is_system", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["scope", "code"],
            },
        ),
        migrations.AddField(
            model_name="personalapikey",
            name="last_used_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="personalapikey",
            name="last_used_user_agent",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="personalapikey",
            name="scopes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="securitytoken",
            name="issued_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="securitytoken",
            name="issued_user_agent",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="usersecuritystate",
            name="access_token_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="usersecuritystate",
            name="last_mfa_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("archived", "Archived"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workspacemembership",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("suspended", "Suspended")],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="securitytoken",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("email_verify", "Email verification"),
                    ("password_reset", "Password reset"),
                    ("refresh", "Refresh token"),
                    ("mfa_challenge", "MFA challenge"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="workspaceinvitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Admin"),
                    ("editor", "Editor"),
                    ("author", "Author"),
                    ("analyst", "Analyst"),
                    ("support", "Support"),
                    ("billing_manager", "Billing manager"),
                    ("viewer", "Viewer"),
                ],
                default="editor",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="workspacemembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Admin"),
                    ("editor", "Editor"),
                    ("author", "Author"),
                    ("analyst", "Analyst"),
                    ("support", "Support"),
                    ("billing_manager", "Billing manager"),
                    ("viewer", "Viewer"),
                ],
                default="viewer",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ImpersonationAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.CharField(blank=True, max_length=280)),
                ("session_key", models.CharField(blank=True, max_length=120)),
                ("request_id", models.CharField(blank=True, max_length=128)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impersonations_started",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impersonations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="MFARecoveryCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code_hash", models.CharField(db_index=True, max_length=128)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_recovery_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MFATOTPDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("secret", models.CharField(max_length=128)),
                ("is_confirmed", models.BooleanField(default=False)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_totp_device",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__username"],
            },
        ),
        migrations.CreateModel(
            name="RBACRolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_roles",
                        to="core.rbacpermission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="core.rbacrole",
                    ),
                ),
            ],
            options={
                "ordering": ["role__code", "permission__code"],
            },
        ),
        migrations.CreateModel(
            name="SiteMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("site_owner", "Site owner"),
                            ("editor", "Editor"),
                            ("author", "Author"),
                            ("analyst", "Analyst"),
                            ("support", "Support"),
                            ("billing_manager", "Billing manager"),
                            ("viewer", "Viewer"),
                        ],
                        default="viewer",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("suspended", "Suspended")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_site_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="core.site",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["site__name", "role", "user__username"],
            },
        ),
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                ("mfa_enabled", models.BooleanField(default=False)),
                ("display_name", models.CharField(blank=True, max_length=160)),
                ("avatar_url", models.URLField(blank=True, max_length=600)),
                ("profile_bio", models.TextField(blank=True)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("locale", models.CharField(default="en", max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("pending", "Pending"),
                            ("locked", "Locked"),
                            ("suspended", "Suspended"),
                            ("deleted", "Deleted"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_support_agent", models.BooleanField(default=False)),
                ("terms_accepted_at", models.DateTimeField(blank=True, null=True)),
                ("privacy_accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "data_processing_consent_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("marketing_opt_in", models.BooleanField(default=False)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__username"],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_key", models.CharField(db_index=True, max_length=120)),
                (
                    "auth_method",
                    models.CharField(
                        choices=[
                            ("session", "Session cookie"),
                            ("access_token", "Access token"),
                            ("api_key", "API key"),
                            ("impersonation", "Impersonation"),
                        ],
                        default="session",
                        max_length=20,
                    ),
                ),
                ("device_id", models.CharField(blank=True, max_length=64)),
                ("device_name", models.CharField(blank=True, max_length=180)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                (
                    "refresh_token_hash",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "impersonated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="impersonated_user_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="securitytoken",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="security_tokens",
                to="core.usersession",
            ),
        ),
        migrations.AddIndex(
            model_name="securitytoken",
            index=models.Index(
                fields=["session", "purpose", "created_at"],
                name="core_securi_session_ea1b1a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="impersonationaudit",
            index=models.Index(
                fields=["actor", "started_at"], name="core_impers_actor_i_5a4c5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="impersonationaudit",
            index=models.Index(
                fields=["target", "started_at"], name="core_impers_target__ff86c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mfarecoverycode",
            index=models.Index(
                fields=["user", "used_at"], name="core_mfarec_user_id_ac1a5d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="rbacrolepermission",
            constraint=models.UniqueConstraint(
                fields=("role", "permission"), name="core_unique_role_permission"
            ),
        ),
        migrations.AddConstraint(
            model_name="sitemembership",
            constraint=models.UniqueConstraint(
                fields=("site", "user"), name="core_unique_site_user"
            ),
        ),
        migrations.AddIndex(
            model_name="useraccount",
            index=models.Index(
                fields=["status", "updated_at"], name="core_userac_status_2b6b55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "revoked_at", "last_seen_at"],
                name="core_userse_user_id_d95c8a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["session_key", "revoked_at"],
                name="core_userse_session_a9052e_idx",
            ),
        ),
        migrations.RunPython(seed_identity_and_rbac, noop_reverse),
    ]
