# Generated by Django 5.2.5 on 2026-04-02 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchConsoleCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_url', models.CharField(blank=True, max_length=500)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gsc_credential', to='core.site')),
            ],
            options={
                'verbose_name': 'Search Console Credential',
            },
        ),
        migrations.CreateModel(
            name='SEOAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audited_url', models.URLField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('title_length', models.IntegerField(default=0)),
                ('meta_description', models.CharField(blank=True, max_length=1000)),
                ('meta_description_length', models.IntegerField(default=0)),
                ('h1_count', models.IntegerField(default=0)),
                ('h1_text', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True, max_length=1000)),
                ('og_title', models.CharField(blank=True, max_length=500)),
                ('og_description', models.CharField(blank=True, max_length=1000)),
                ('og_image', models.URLField(blank=True, max_length=1000)),
                ('response_time_ms', models.IntegerField(default=0)),
                ('status_code', models.IntegerField(default=0)),
                ('word_count', models.IntegerField(default=0)),
                ('image_count', models.IntegerField(default=0)),
                ('images_missing_alt', models.IntegerField(default=0)),
                ('internal_links', models.IntegerField(default=0)),
                ('external_links', models.IntegerField(default=0)),
                ('has_schema_markup', models.BooleanField(default=False)),
                ('is_mobile_friendly', models.BooleanField(default=False)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo_audits', to='cms.page')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_audits', to='core.site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit_schedule', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('manual', 'Manual only')], default='manual', max_length=20)),
                ('alert_score_threshold', models.IntegerField(default=60)),
                ('gsc_property_url', models.CharField(blank=True, max_length=500)),
                ('sitemap_url', models.CharField(blank=True, max_length=1000)),
                ('notify_on_issues', models.BooleanField(default=False)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo_settings', to='core.site')),
            ],
            options={
                'verbose_name': 'SEO Settings',
                'verbose_name_plural': 'SEO Settings',
            },
        ),
        migrations.CreateModel(
            name='TrackedKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyword', models.CharField(max_length=255)),
                ('target_url', models.CharField(blank=True, max_length=1000)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_keywords', to='core.site')),
            ],
            options={
                'ordering': ['keyword'],
            },
        ),
        migrations.CreateModel(
            name='KeywordRankEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('position', models.FloatField(blank=True, null=True)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('url', models.CharField(blank=True, max_length=1000)),
                ('source', models.CharField(default='manual', max_length=40)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_entries', to='analytics.trackedkeyword')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SEOAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('average_position', models.FloatField(default=0.0)),
                ('ctr', models.FloatField(default=0.0)),
                ('source', models.CharField(default='google_search_console', max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo_analytics', to='cms.page')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_analytics', to='core.site')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('site', 'page', 'date', 'source'), name='analytics_unique_seo_analytics_entry')],
            },
        ),
        migrations.AddConstraint(
            model_name='trackedkeyword',
            constraint=models.UniqueConstraint(fields=('site', 'keyword'), name='analytics_unique_site_keyword'),
        ),
        migrations.AddConstraint(
            model_name='keywordrankentry',
            constraint=models.UniqueConstraint(fields=('keyword', 'date', 'source'), name='analytics_unique_keyword_rank_entry'),
        ),
    ]
