# Generated by Django 5.2.5 on 2026-04-19 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        ("core", "0003_rbacpermission_rbacrole_personalapikey_last_used_ip_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommerceAnalyticsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_name",
                    models.CharField(
                        choices=[
                            ("product.view", "Product view"),
                            ("cart.add", "Add to cart"),
                            ("checkout.begin", "Begin checkout"),
                            ("order.purchase", "Purchase"),
                            ("order.refund", "Refund"),
                        ],
                        max_length=60,
                    ),
                ),
                ("aggregate_type", models.CharField(blank=True, max_length=60)),
                ("aggregate_id", models.CharField(blank=True, max_length=120)),
                ("request_id", models.CharField(blank=True, max_length=128)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commerce_analytics_events",
                        to="core.site",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["site", "event_name", "created_at"],
                        name="analytics_c_site_id_5dfbb6_idx",
                    ),
                    models.Index(
                        fields=["site", "aggregate_type", "aggregate_id"],
                        name="analytics_c_site_id_0323a2_idx",
                    ),
                ],
            },
        ),
    ]
