# Generated by Django 5.2.5 on 2026-04-20 16:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_commerceanalyticsevent"),
        ("core", "0003_rbacpermission_rbacrole_personalapikey_last_used_ip_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_key",
                    models.CharField(db_index=True, default=uuid.uuid4, max_length=64),
                ),
                ("started_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("landing_path", models.CharField(blank=True, max_length=255)),
                ("exit_path", models.CharField(blank=True, max_length=255)),
                ("referrer", models.CharField(blank=True, max_length=500)),
                ("referrer_domain", models.CharField(blank=True, max_length=255)),
                ("utm_source", models.CharField(blank=True, max_length=120)),
                ("utm_medium", models.CharField(blank=True, max_length=120)),
                ("utm_campaign", models.CharField(blank=True, max_length=120)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("desktop", "Desktop"),
                            ("mobile", "Mobile"),
                            ("tablet", "Tablet"),
                            ("bot", "Bot"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("browser", models.CharField(blank=True, max_length=120)),
                ("os", models.CharField(blank=True, max_length=120)),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                ("ip_prefix", models.CharField(blank=True, max_length=64)),
                ("user_agent_hash", models.CharField(blank=True, max_length=64)),
                ("is_bot", models.BooleanField(default=False)),
                ("page_view_count", models.PositiveIntegerField(default=0)),
                ("event_count", models.PositiveIntegerField(default=0)),
                ("conversion_count", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_sessions",
                        to="core.site",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_sessions",
                "ordering": ["-last_seen_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_name", models.CharField(default="page_view", max_length=120)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("page_view", "Page view"),
                            ("event", "Event"),
                            ("conversion", "Conversion"),
                            ("funnel", "Funnel"),
                        ],
                        default="event",
                        max_length=20,
                    ),
                ),
                ("path", models.CharField(blank=True, max_length=255)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("referrer", models.CharField(blank=True, max_length=500)),
                ("referrer_domain", models.CharField(blank=True, max_length=255)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("desktop", "Desktop"),
                            ("mobile", "Mobile"),
                            ("tablet", "Tablet"),
                            ("bot", "Bot"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("browser", models.CharField(blank=True, max_length=120)),
                ("os", models.CharField(blank=True, max_length=120)),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_bot", models.BooleanField(default=False)),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                ("ip_prefix", models.CharField(blank=True, max_length=64)),
                ("user_agent_hash", models.CharField(blank=True, max_length=64)),
                ("properties", models.JSONField(blank=True, default=dict)),
                ("occurred_at", models.DateTimeField()),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_events",
                        to="core.site",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="analytics.analyticssession",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_events",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="SearchDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("index_name", models.CharField(max_length=60)),
                ("external_id", models.CharField(max_length=120)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("path", models.CharField(blank=True, max_length=255)),
                ("content", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("source_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_documents",
                        to="core.site",
                    ),
                ),
            ],
            options={
                "db_table": "search_documents",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="analyticssession",
            index=models.Index(
                fields=["site", "last_seen_at"], name="analytics_s_site_id_c301e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analyticssession",
            index=models.Index(
                fields=["site", "is_bot", "last_seen_at"],
                name="analytics_s_site_id_2fac13_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analyticssession",
            index=models.Index(
                fields=["site", "started_at"], name="analytics_s_site_id_075b27_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="analyticssession",
            constraint=models.UniqueConstraint(
                fields=("site", "session_key"), name="analytics_unique_site_session_key"
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["site", "event_type", "occurred_at"],
                name="analytics_e_site_id_f439d2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["site", "event_name", "occurred_at"],
                name="analytics_e_site_id_9792b6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["site", "path", "occurred_at"],
                name="analytics_e_site_id_8605c1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["session", "occurred_at"], name="analytics_e_session_a66e77_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchdocument",
            index=models.Index(
                fields=["site", "index_name", "updated_at"],
                name="search_docu_site_id_bb3e84_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="searchdocument",
            index=models.Index(
                fields=["site", "path"], name="search_docu_site_id_87d6d4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="searchdocument",
            constraint=models.UniqueConstraint(
                fields=("site", "index_name", "external_id"),
                name="analytics_unique_search_document",
            ),
        ),
    ]
