# Generated by Django 5.2.5 on 2026-04-20 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_analyticssession_analyticsevent_searchdocument_and_more"),
        ("core", "0003_rbacpermission_rbacrole_personalapikey_last_used_ip_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsRollup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period",
                    models.CharField(
                        choices=[("daily", "Daily")], default="daily", max_length=20
                    ),
                ),
                ("period_date", models.DateField()),
                ("page_views", models.PositiveIntegerField(default=0)),
                ("events", models.PositiveIntegerField(default=0)),
                ("conversions", models.PositiveIntegerField(default=0)),
                ("sessions", models.PositiveIntegerField(default=0)),
                (
                    "total_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_rollups",
                        to="core.site",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_rollups",
                "ordering": ["-period_date", "site_id"],
                "indexes": [
                    models.Index(
                        fields=["site", "period", "period_date"],
                        name="analytics_r_site_id_9db084_idx",
                    ),
                    models.Index(
                        fields=["period", "period_date"],
                        name="analytics_r_period_42d128_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("site", "period", "period_date"),
                        name="analytics_unique_rollup_period",
                    )
                ],
            },
        ),
    ]
