# Generated by Django 5.2.5 on 2026-04-19 11:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0006_mediaasset_content_signature_mediaasset_deleted_at_and_more"),
        ("commerce", "0001_initial"),
        ("core", "0003_rbacpermission_rbacrole_personalapikey_last_used_ip_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckoutSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token",
                    models.CharField(default=uuid.uuid4, max_length=48, unique=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("currency", models.CharField(default="USD", max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("shipping_address", models.JSONField(blank=True, default=dict)),
                ("billing_address", models.JSONField(blank=True, default=dict)),
                ("discount_code", models.CharField(blank=True, max_length=50)),
                ("shipping_rate_id", models.IntegerField(blank=True, null=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "shipping_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tax_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("pricing_details", models.JSONField(blank=True, default=dict)),
                ("expires_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommerceEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("product.view", "Product view"),
                            ("cart.add", "Add to cart"),
                            ("checkout.begin", "Begin checkout"),
                            ("order.purchase", "Purchase"),
                            ("order.refund", "Refund"),
                        ],
                        max_length=60,
                    ),
                ),
                ("aggregate_type", models.CharField(blank=True, max_length=60)),
                ("aggregate_id", models.CharField(blank=True, max_length=120)),
                ("request_id", models.CharField(blank=True, max_length=128)),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254)),
                ("first_name", models.CharField(blank=True, max_length=120)),
                ("last_name", models.CharField(blank=True, max_length=120)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("newsletter_consent", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("last_order_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-updated_at", "email"],
            },
        ),
        migrations.CreateModel(
            name="CustomerAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(blank=True, max_length=80)),
                ("first_name", models.CharField(blank=True, max_length=120)),
                ("last_name", models.CharField(blank=True, max_length=120)),
                ("company", models.CharField(blank=True, max_length=160)),
                ("line1", models.CharField(max_length=220)),
                ("line2", models.CharField(blank=True, max_length=220)),
                ("city", models.CharField(max_length=120)),
                ("state", models.CharField(blank=True, max_length=120)),
                ("postal_code", models.CharField(blank=True, max_length=32)),
                ("country", models.CharField(max_length=2)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("is_default_shipping", models.BooleanField(default=False)),
                ("is_default_billing", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-is_default_shipping", "-is_default_billing", "id"],
            },
        ),
        migrations.CreateModel(
            name="FraudSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("signal_type", models.CharField(default="generic", max_length=80)),
                (
                    "score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("on_hand", models.IntegerField(default=0)),
                ("reserved", models.IntegerField(default=0)),
                ("low_stock_threshold", models.PositiveIntegerField(default=5)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(max_length=80)),
                ("message", models.CharField(blank=True, max_length=280)),
                ("request_id", models.CharField(blank=True, max_length=128)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(default="stripe", max_length=80)),
                ("provider_payment_id", models.CharField(blank=True, max_length=180)),
                (
                    "idempotency_key",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("currency", models.CharField(default="USD", max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially refunded"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("error_message", models.TextField(blank=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("rules", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_url", models.URLField(blank=True, max_length=1000)),
                ("alt_text", models.CharField(blank=True, max_length=280)),
                ("position", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider_refund_id", models.CharField(blank=True, max_length=180)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("currency", models.CharField(default="USD", max_length=8)),
                ("reason", models.CharField(blank=True, max_length=240)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(blank=True, max_length=80)),
                ("carrier", models.CharField(blank=True, max_length=120)),
                ("service_level", models.CharField(blank=True, max_length=120)),
                ("tracking_number", models.CharField(blank=True, max_length=180)),
                ("tracking_url", models.URLField(blank=True, max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("committed", "Committed"),
                            ("released", "Released"),
                            ("expired", "Expired"),
                        ],
                        default="reserved",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaxRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(default="internal", max_length=80)),
                ("jurisdiction", models.CharField(blank=True, max_length=180)),
                (
                    "rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                (
                    "taxable_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("currency", models.CharField(default="USD", max_length=8)),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="cart",
            name="discount_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carts",
                to="commerce.discountcode",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cart",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="discountcode",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="order",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="fraud_score",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="order",
            name="fulfilled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="fulfillment_status",
            field=models.CharField(
                choices=[
                    ("unfulfilled", "Unfulfilled"),
                    ("partial", "Partial"),
                    ("fulfilled", "Fulfilled"),
                    ("cancelled", "Cancelled"),
                ],
                default="unfulfilled",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="refunded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="refunds_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="order",
            name="source",
            field=models.CharField(
                choices=[
                    ("storefront", "Storefront"),
                    ("admin", "Admin"),
                    ("api", "API"),
                ],
                default="storefront",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_taxable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("physical", "Physical"),
                    ("digital", "Digital"),
                    ("service", "Service"),
                ],
                default="physical",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="requires_shipping",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="seo_description",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="product",
            name="seo_title",
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="allow_backorder",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="barcode",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="cost_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="inventory_state",
            field=models.CharField(
                choices=[
                    ("in_stock", "In stock"),
                    ("low_stock", "Low stock"),
                    ("out_of_stock", "Out of stock"),
                    ("backorder", "Backorder"),
                    ("preorder", "Preorder"),
                ],
                default="in_stock",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="low_stock_threshold",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="weight_grams",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="shippingrate",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                    ("partially_refunded", "Partially refunded"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="shippingrate",
            constraint=models.UniqueConstraint(
                fields=("zone", "method_code"),
                name="commerce_unique_shipping_rate_method_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="shippingzone",
            constraint=models.UniqueConstraint(
                fields=("site", "name"), name="commerce_unique_site_shipping_zone_name"
            ),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkout_sessions",
                to="commerce.cart",
            ),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkout_sessions",
                to="core.site",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="checkout_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="commerce.checkoutsession",
            ),
        ),
        migrations.AddField(
            model_name="commerceevent",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commerce_events",
                to="core.site",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="core.site",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commerce_customers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checkout_sessions",
                to="commerce.customer",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carts",
                to="commerce.customer",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="commerce.customer",
            ),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["site", "status", "updated_at"],
                name="commerce_ca_site_id_7a1240_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["site", "order_number"], name="commerce_or_site_id_42dd4c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["site", "status", "placed_at"],
                name="commerce_or_site_id_15dba1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["site", "payment_status", "placed_at"],
                name="commerce_or_site_id_b31c82_idx",
            ),
        ),
        migrations.AddField(
            model_name="customeraddress",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="commerce.customer",
            ),
        ),
        migrations.AddField(
            model_name="fraudsignal",
            name="checkout_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fraud_signals",
                to="commerce.checkoutsession",
            ),
        ),
        migrations.AddField(
            model_name="fraudsignal",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fraud_signals",
                to="commerce.order",
            ),
        ),
        migrations.AddField(
            model_name="fraudsignal",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fraud_signals",
                to="core.site",
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="variant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_record",
                to="commerce.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="orderauditlog",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commerce_audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orderauditlog",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="commerce.order",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="commerce.order",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="core.site",
            ),
        ),
        migrations.AddField(
            model_name="productcollection",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_collections",
                to="core.site",
            ),
        ),
        migrations.AddField(
            model_name="discountcode",
            name="applies_to_collections",
            field=models.ManyToManyField(
                blank=True,
                related_name="discount_codes",
                to="commerce.productcollection",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="collections",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="commerce.productcollection"
            ),
        ),
        migrations.AddField(
            model_name="productmedia",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_media_links",
                to="cms.mediaasset",
            ),
        ),
        migrations.AddField(
            model_name="productmedia",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_items",
                to="commerce.product",
            ),
        ),
        migrations.AddField(
            model_name="productmedia",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_items",
                to="commerce.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refunds",
                to="commerce.order",
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refunds",
                to="commerce.payment",
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refunds",
                to="core.site",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipments",
                to="commerce.order",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipping_rate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipments",
                to="commerce.shippingrate",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipments",
                to="core.site",
            ),
        ),
        migrations.AddField(
            model_name="stockreservation",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_reservations",
                to="commerce.cart",
            ),
        ),
        migrations.AddField(
            model_name="stockreservation",
            name="checkout_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_reservations",
                to="commerce.checkoutsession",
            ),
        ),
        migrations.AddField(
            model_name="stockreservation",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_reservations",
                to="commerce.order",
            ),
        ),
        migrations.AddField(
            model_name="stockreservation",
            name="product_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_reservations",
                to="commerce.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="stockreservation",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_reservations",
                to="core.site",
            ),
        ),
        migrations.AddField(
            model_name="taxrecord",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tax_records",
                to="commerce.order",
            ),
        ),
        migrations.AddField(
            model_name="taxrecord",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tax_records",
                to="core.site",
            ),
        ),
        migrations.AddIndex(
            model_name="commerceevent",
            index=models.Index(
                fields=["site", "event_type", "created_at"],
                name="commerce_co_site_id_de2988_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["site", "email"], name="commerce_cu_site_id_5a90a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["site", "last_order_at"], name="commerce_cu_site_id_b624c1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                fields=("site", "email"), name="commerce_unique_site_customer_email"
            ),
        ),
        migrations.AddIndex(
            model_name="checkoutsession",
            index=models.Index(
                fields=["site", "status", "expires_at"],
                name="commerce_ch_site_id_a215a4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="checkoutsession",
            index=models.Index(
                fields=["token", "status"], name="commerce_ch_token_94d56d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customeraddress",
            index=models.Index(
                fields=["customer", "is_default_shipping"],
                name="commerce_cu_custome_a55c88_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customeraddress",
            index=models.Index(
                fields=["customer", "is_default_billing"],
                name="commerce_cu_custome_9f8143_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fraudsignal",
            index=models.Index(
                fields=["site", "signal_type", "created_at"],
                name="commerce_fr_site_id_55986a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="orderauditlog",
            index=models.Index(
                fields=["order", "action", "created_at"],
                name="commerce_or_order_i_5fc5e0_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                fields=("site", "provider", "provider_payment_id"),
                name="commerce_unique_provider_payment_per_site",
            ),
        ),
        migrations.AddConstraint(
            model_name="productcollection",
            constraint=models.UniqueConstraint(
                fields=("site", "slug"),
                name="commerce_unique_site_product_collection_slug",
            ),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(
                fields=["site", "status", "created_at"],
                name="commerce_re_site_id_98ddca_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["site", "status", "created_at"],
                name="commerce_sh_site_id_0ee96c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(
                fields=["site", "status", "expires_at"],
                name="commerce_st_site_id_5349fb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(
                fields=["product_variant", "status"],
                name="commerce_st_product_d25ca9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taxrecord",
            index=models.Index(
                fields=["site", "order", "provider"],
                name="commerce_ta_site_id_78807f_idx",
            ),
        ),
    ]
