# Generated by Django 5.2.5 on 2026-04-02 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=180)),
                ('path', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('is_homepage', models.BooleanField(default=False)),
                ('seo', models.JSONField(blank=True, default=dict)),
                ('page_settings', models.JSONField(blank=True, default=dict)),
                ('builder_data', models.JSONField(blank=True, default=dict)),
                ('html', models.TextField(blank=True)),
                ('css', models.TextField(blank=True)),
                ('js', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Schedule publish time', null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.site')),
            ],
            options={
                'ordering': ['-is_homepage', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=180)),
                ('path', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('seo', models.JSONField(blank=True, default=dict)),
                ('page_settings', models.JSONField(blank=True, default=dict)),
                ('builder_data', models.JSONField(blank=True, default=dict)),
                ('html', models.TextField(blank=True)),
                ('css', models.TextField(blank=True)),
                ('js', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_translations', to='core.sitelocale')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cms.page')),
            ],
            options={
                'ordering': ['locale__code', 'title'],
            },
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('site', 'path'), name='cms_unique_site_path'),
        ),
        migrations.AddConstraint(
            model_name='pagetranslation',
            constraint=models.UniqueConstraint(fields=('page', 'locale'), name='cms_unique_page_locale_translation'),
        ),
        migrations.AddConstraint(
            model_name='pagetranslation',
            constraint=models.UniqueConstraint(fields=('locale', 'path'), name='cms_unique_locale_translation_path'),
        ),
    ]
