# Generated by Django 5.2.5 on 2026-04-02 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('hero', 'Hero'), ('feature', 'Feature'), ('cta', 'Call to Action'), ('testimonial', 'Testimonial'), ('pricing', 'Pricing'), ('faq', 'FAQ'), ('footer', 'Footer'), ('header', 'Header'), ('content', 'Content'), ('gallery', 'Gallery'), ('form', 'Form'), ('other', 'Other')], default='other', max_length=40)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('builder_data', models.JSONField(blank=True, default=dict)),
                ('html', models.TextField(blank=True)),
                ('css', models.TextField(blank=True)),
                ('is_global', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('usage_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('marketplace', 'Marketplace'), ('disabled', 'Disabled')], default='published', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('plan_required', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('author', models.CharField(blank=True, max_length=140)),
                ('preview_url', models.URLField(blank=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_templates', to='core.site')),
            ],
            options={
                'ordering': ['-is_global', '-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MediaFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('path', models.CharField(max_length=500)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='cms.mediafolder')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_folders', to='core.site')),
            ],
            options={
                'ordering': ['path', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('caption', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('video', 'Video'), ('other', 'Other')], default='other', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='core.site')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='cms.mediafolder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=160)),
                ('location', models.CharField(default='header', max_length=60)),
                ('items', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigation_menus', to='core.site')),
            ],
            options={
                'ordering': ['location', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RobotsTxt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(default='User-agent: *\nAllow: /')),
                ('is_custom', models.BooleanField(default=False)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='robots_txt', to='core.site')),
            ],
            options={
                'verbose_name': 'Robots.txt',
                'verbose_name_plural': 'Robots.txt',
            },
        ),
        migrations.CreateModel(
            name='URLRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_path', models.CharField(max_length=500)),
                ('target_path', models.CharField(max_length=500)),
                ('redirect_type', models.CharField(choices=[('301', '301 Permanent'), ('302', '302 Temporary')], default='301', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('hit_count', models.IntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirects', to='core.site')),
            ],
            options={
                'ordering': ['site', 'source_path'],
            },
        ),
        migrations.AddConstraint(
            model_name='mediafolder',
            constraint=models.UniqueConstraint(fields=('site', 'path'), name='unique_site_folder_path'),
        ),
        migrations.AddConstraint(
            model_name='navigationmenu',
            constraint=models.UniqueConstraint(fields=('site', 'slug'), name='unique_site_menu_slug'),
        ),
        migrations.AddConstraint(
            model_name='urlredirect',
            constraint=models.UniqueConstraint(fields=('site', 'source_path'), name='unique_site_redirect_source'),
        ),
    ]
