# Generated by Django 5.2.5 on 2026-04-03

from django.db import migrations, models


def _normalize_existing_page_content(apps, schema_editor):
    from cms.page_schema import normalize_page_content

    Page = apps.get_model("cms", "Page")
    PageTranslation = apps.get_model("cms", "PageTranslation")

    for page in Page.objects.all().iterator():
        normalized = normalize_page_content(
            title=page.title,
            slug=page.slug,
            path=page.path,
            is_homepage=bool(page.is_homepage),
            status=page.status,
            locale_code="",
            builder_data=page.builder_data,
            seo=page.seo,
            page_settings=page.page_settings,
            html=page.html,
            css=page.css,
            js=page.js,
            schema_version=getattr(page, "builder_schema_version", 1),
            strict=False,
        )
        page.builder_schema_version = normalized["schema_version"]
        page.builder_data = normalized["builder_data"]
        page.seo = normalized["seo"]
        page.page_settings = normalized["page_settings"]
        page.html = normalized["html"]
        page.css = normalized["css"]
        page.js = normalized["js"]
        page.save(
            update_fields=[
                "builder_schema_version",
                "builder_data",
                "seo",
                "page_settings",
                "html",
                "css",
                "js",
                "updated_at",
            ]
        )

    for translation in PageTranslation.objects.select_related("locale", "page").all().iterator():
        locale_code = translation.locale.code if translation.locale_id else ""
        normalized = normalize_page_content(
            title=translation.title,
            slug=translation.slug,
            path=translation.path,
            is_homepage=bool(translation.page.is_homepage),
            status=translation.status,
            locale_code=locale_code,
            builder_data=translation.builder_data,
            seo=translation.seo,
            page_settings=translation.page_settings,
            html=translation.html,
            css=translation.css,
            js=translation.js,
            schema_version=getattr(translation, "builder_schema_version", 1),
            strict=False,
        )
        translation.builder_schema_version = normalized["schema_version"]
        translation.builder_data = normalized["builder_data"]
        translation.seo = normalized["seo"]
        translation.page_settings = normalized["page_settings"]
        translation.html = normalized["html"]
        translation.css = normalized["css"]
        translation.js = normalized["js"]
        translation.save(
            update_fields=[
                "builder_schema_version",
                "builder_data",
                "seo",
                "page_settings",
                "html",
                "css",
                "js",
                "updated_at",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_blocktemplate_mediafolder_mediaasset_navigationmenu_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="builder_schema_version",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="pagetranslation",
            name="builder_schema_version",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.RunPython(_normalize_existing_page_content, migrations.RunPython.noop),
    ]
