# Generated by Django 5.2.5 on 2026-04-03

from django.db import migrations, models


def _upgrade_content_contracts(apps, schema_editor):
    from cms.page_schema import normalize_block_template_builder_data, normalize_block_template_renderer_key, normalize_page_content

    BlockTemplate = apps.get_model("cms", "BlockTemplate")
    Page = apps.get_model("cms", "Page")
    PageTranslation = apps.get_model("cms", "PageTranslation")

    for page in Page.objects.all().iterator():
        normalized = normalize_page_content(
            title=page.title,
            slug=page.slug,
            path=page.path,
            is_homepage=bool(page.is_homepage),
            status=page.status,
            locale_code="",
            builder_data=page.builder_data,
            seo=page.seo,
            page_settings=page.page_settings,
            html=page.html,
            css=page.css,
            js=page.js,
            schema_version=getattr(page, "builder_schema_version", 2),
            strict=False,
        )
        page.builder_schema_version = normalized["schema_version"]
        page.builder_data = normalized["builder_data"]
        page.seo = normalized["seo"]
        page.page_settings = normalized["page_settings"]
        page.html = normalized["html"]
        page.css = normalized["css"]
        page.js = normalized["js"]
        page.save(
            update_fields=[
                "builder_schema_version",
                "builder_data",
                "seo",
                "page_settings",
                "html",
                "css",
                "js",
                "updated_at",
            ]
        )

    for translation in PageTranslation.objects.select_related("locale", "page").all().iterator():
        locale_code = translation.locale.code if translation.locale_id else ""
        normalized = normalize_page_content(
            title=translation.title,
            slug=translation.slug,
            path=translation.path,
            is_homepage=bool(translation.page.is_homepage),
            status=translation.status,
            locale_code=locale_code,
            builder_data=translation.builder_data,
            seo=translation.seo,
            page_settings=translation.page_settings,
            html=translation.html,
            css=translation.css,
            js=translation.js,
            schema_version=getattr(translation, "builder_schema_version", 2),
            strict=False,
        )
        translation.builder_schema_version = normalized["schema_version"]
        translation.builder_data = normalized["builder_data"]
        translation.seo = normalized["seo"]
        translation.page_settings = normalized["page_settings"]
        translation.html = normalized["html"]
        translation.css = normalized["css"]
        translation.js = normalized["js"]
        translation.save(
            update_fields=[
                "builder_schema_version",
                "builder_data",
                "seo",
                "page_settings",
                "html",
                "css",
                "js",
                "updated_at",
            ]
        )

    for template in BlockTemplate.objects.all().iterator():
        renderer_key = normalize_block_template_renderer_key(
            getattr(template, "renderer_key", ""),
            category=template.category,
            strict=False,
        )
        default_props_schema = (
            template.default_props_schema if isinstance(template.default_props_schema, dict) else {}
        )
        compatibility_flags = (
            template.compatibility_flags if isinstance(template.compatibility_flags, dict) else {}
        )
        version = int(template.version or 1) if str(template.version or "").isdigit() else 1
        if version < 1:
            version = 1

        template.renderer_key = renderer_key
        template.default_props_schema = default_props_schema
        template.compatibility_flags = compatibility_flags
        template.version = version
        template.builder_data = normalize_block_template_builder_data(
            template.builder_data,
            renderer_key=renderer_key,
            strict=False,
        )
        template.save(
            update_fields=[
                "renderer_key",
                "default_props_schema",
                "compatibility_flags",
                "version",
                "builder_data",
                "updated_at",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0003_page_schema_version_and_builder_data_normalization"),
    ]

    operations = [
        migrations.AddField(
            model_name="blocktemplate",
            name="compatibility_flags",
            field=models.JSONField(blank=True, default=dict, help_text="Runtime compatibility toggles (for example, requires_blog, requires_commerce)."),
        ),
        migrations.AddField(
            model_name="blocktemplate",
            name="default_props_schema",
            field=models.JSONField(blank=True, default=dict, help_text="Default props contract passed to the runtime component."),
        ),
        migrations.AddField(
            model_name="blocktemplate",
            name="renderer_key",
            field=models.CharField(default="core.rich-text", help_text="Stable Next.js component registry key used to render this template.", max_length=120),
        ),
        migrations.AddField(
            model_name="blocktemplate",
            name="version",
            field=models.PositiveSmallIntegerField(default=1, help_text="Template contract version for renderer compatibility checks."),
        ),
        migrations.AlterField(
            model_name="page",
            name="builder_schema_version",
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="pagetranslation",
            name="builder_schema_version",
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.RunPython(_upgrade_content_contracts, migrations.RunPython.noop),
    ]
