# Generated by Django 5.2.5 on 2026-04-19 08:35

import shared.storage.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0004_renderer_contract_and_block_template_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaasset",
            name="file",
            field=models.FileField(
                upload_to=shared.storage.uploads.secure_media_upload_path
            ),
        ),
    ]
