# Generated by Django 5.2.5 on 2026-04-20 16:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_rbacpermission_rbacrole_personalapikey_last_used_ip_and_more"),
        ("jobs", "0002_job_jobs_job_status_0ebd7d_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("page_outline", "Page outline"),
                            ("blog_draft", "Blog draft"),
                            ("product_description", "Product description"),
                            ("seo_meta", "SEO metadata"),
                            ("image_alt_text", "Image alt text"),
                            ("faq_schema", "FAQ schema"),
                            ("section_composition", "Section composition"),
                        ],
                        max_length=40,
                    ),
                ),
                ("provider", models.CharField(default="mock", max_length=40)),
                ("model_name", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("prompt", models.TextField()),
                ("sanitized_prompt", models.TextField(blank=True)),
                ("input_payload", models.JSONField(blank=True, default=dict)),
                ("output_payload", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("moderation_flags", models.JSONField(blank=True, default=list)),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("completion_tokens", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                (
                    "estimated_cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "queue_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_jobs",
                        to="jobs.job",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_ai_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_jobs",
                        to="core.site",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_jobs",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIModerationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[("prompt", "Prompt"), ("output", "Output")],
                        max_length=20,
                    ),
                ),
                ("blocked", models.BooleanField(default=False)),
                ("reasons", models.JSONField(blank=True, default=list)),
                ("raw_excerpt", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_logs",
                        to="provider.aijob",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIUsageQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("feature", models.CharField(default="*", max_length=40)),
                (
                    "period",
                    models.CharField(
                        choices=[("daily", "Daily"), ("monthly", "Monthly")],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("max_requests", models.PositiveIntegerField(default=1000)),
                ("max_tokens", models.PositiveIntegerField(default=1000000)),
                (
                    "max_cost_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("reset_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage_quotas",
                        to="core.site",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage_quotas",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AIUsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("feature", models.CharField(default="", max_length=40)),
                ("provider", models.CharField(default="mock", max_length=40)),
                ("model_name", models.CharField(blank=True, max_length=120)),
                ("request_count", models.PositiveIntegerField(default=1)),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("completion_tokens", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                ("status", models.CharField(default="completed", max_length=20)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_records",
                        to="provider.aijob",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage_records",
                        to="core.site",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage_records",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="aijob",
            index=models.Index(
                fields=["workspace", "status", "created_at"],
                name="provider_ai_workspa_26b5c7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aijob",
            index=models.Index(
                fields=["site", "status", "created_at"],
                name="provider_ai_site_id_4a3603_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aijob",
            index=models.Index(
                fields=["feature", "status", "created_at"],
                name="provider_ai_feature_23fc1f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aimoderationlog",
            index=models.Index(
                fields=["job", "stage", "created_at"],
                name="provider_ai_job_id_c17af8_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiusagequota",
            constraint=models.UniqueConstraint(
                fields=("workspace", "site", "feature", "period"),
                name="provider_unique_ai_quota_scope",
            ),
        ),
        migrations.AddIndex(
            model_name="aiusagerecord",
            index=models.Index(
                fields=["workspace", "created_at"],
                name="provider_ai_workspa_ed1d24_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiusagerecord",
            index=models.Index(
                fields=["site", "created_at"], name="provider_ai_site_id_f6e99c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiusagerecord",
            index=models.Index(
                fields=["feature", "created_at"], name="provider_ai_feature_094292_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiusagerecord",
            index=models.Index(
                fields=["provider", "created_at"], name="provider_ai_provide_5cec48_idx"
            ),
        ),
    ]
