# Generated by Django 5.2.5 on 2026-04-19 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        ("core", "0003_rbacpermission_rbacrole_personalapikey_last_used_ip_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="flagged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="comment",
            name="moderation_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="moderation_state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("spam", "Spam"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="spam_provider",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="comment",
            name="spam_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="post",
            name="author_byline",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="post",
            name="moderation_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post",
            name="related_posts",
            field=models.ManyToManyField(
                blank=True, related_name="related_to_posts", to="blog.post"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_review", "In review"),
                    ("scheduled", "Scheduled"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BlogAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("display_name", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=180)),
                ("bio", models.TextField(blank=True)),
                ("avatar_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_authors",
                        to="core.site",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_author_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
        migrations.AddField(
            model_name="post",
            name="primary_author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_posts",
                to="blog.blogauthor",
            ),
        ),
        migrations.AddConstraint(
            model_name="blogauthor",
            constraint=models.UniqueConstraint(
                fields=("site", "slug"), name="blog_unique_site_author_slug"
            ),
        ),
    ]
