# Generated by Django 5.2.5 on 2026-04-02 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('dns_provider', models.CharField(blank=True, max_length=50)),
                ('registrar', models.CharField(blank=True, max_length=50)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_mappings', to='core.site')),
            ],
            options={
                'ordering': ['domain'],
            },
        ),
        migrations.CreateModel(
            name='SSLCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cert_file', models.TextField()),
                ('key_file', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('domain_mapping', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='domains.domainmapping')),
            ],
            options={
                'ordering': ['expires_at'],
            },
        ),
    ]
