# Generated by Django 5.2.5 on 2026-04-02 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255)),
                ('available', models.BooleanField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, default='USD', max_length=10)),
                ('registrar', models.CharField(blank=True, max_length=140)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['domain_name', 'checked_at'], name='domains_dom_domain__b60db4_idx')],
            },
        ),
        migrations.CreateModel(
            name='DomainContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('registrant', 'Registrant'), ('admin', 'Administrative'), ('tech', 'Technical'), ('billing', 'Billing')], default='registrant', max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('organization', models.CharField(blank=True, max_length=140)),
                ('address1', models.CharField(blank=True, max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code', max_length=2)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_contacts', to='core.site')),
            ],
            options={
                'ordering': ['role', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain_name', models.CharField(max_length=255, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('failed', 'Verification Failed')], default='pending', max_length=20)),
                ('verification_token', models.CharField(blank=True, max_length=100)),
                ('verification_method', models.CharField(blank=True, choices=[('dns_txt', 'DNS TXT Record'), ('file', 'File Upload')], default='dns_txt', max_length=40)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_verification_attempt', models.DateTimeField(blank=True, null=True)),
                ('verification_error', models.TextField(blank=True)),
                ('registration_status', models.CharField(choices=[('unregistered', 'Unregistered / External'), ('active', 'Active'), ('expired', 'Expired'), ('pending_transfer', 'Pending Transfer'), ('pending_delete', 'Pending Delete'), ('locked', 'Locked')], default='unregistered', max_length=30)),
                ('registrar', models.CharField(blank=True, max_length=140)),
                ('registrar_account', models.CharField(blank=True, max_length=140)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('privacy_enabled', models.BooleanField(default=False)),
                ('transfer_lock', models.BooleanField(default=True)),
                ('auth_code', models.CharField(blank=True, max_length=255)),
                ('ssl_enabled', models.BooleanField(default=False)),
                ('ssl_expires_at', models.DateTimeField(blank=True, null=True)),
                ('dns_records', models.JSONField(blank=True, default=list)),
                ('nameservers', models.JSONField(blank=True, default=list)),
                ('whois_data', models.JSONField(blank=True, default=dict)),
                ('whois_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='core.site')),
                ('registrant_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domains_as_registrant', to='domains.domaincontact')),
            ],
            options={
                'ordering': ['-is_primary', 'domain_name'],
            },
        ),
    ]
