# Generated by Django 5.2.5 on 2026-04-02 16:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Fully qualified domain name for email hosting', max_length=253, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verifying', 'Verifying'), ('active', 'Active'), ('failed', 'Failed'), ('suspended', 'Suspended')], default='pending', help_text='Current verification state of the email domain', max_length=20)),
                ('verification_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token used for DNS verification')),
                ('verified_at', models.DateTimeField(blank=True, help_text='Timestamp when domain was verified', null=True)),
                ('mx_record', models.CharField(blank=True, help_text='MX record for email routing', max_length=255)),
                ('spf_record', models.TextField(blank=True, help_text='SPF record for email authentication')),
                ('dkim_record', models.TextField(blank=True, help_text='DKIM record for email signing')),
                ('dmarc_record', models.TextField(blank=True, help_text='DMARC record for email policy')),
                ('site', models.ForeignKey(help_text='Site that owns this email domain', on_delete=django.db.models.deletion.CASCADE, related_name='email_domains', to='core.site')),
                ('workspace', models.ForeignKey(help_text='Workspace that owns this domain', on_delete=django.db.models.deletion.CASCADE, related_name='email_domains', to='core.workspace')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('site', 'name')},
            },
        ),
        migrations.CreateModel(
            name='EmailProvisioningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_type', models.CharField(choices=[('create_domain', 'Create Domain'), ('delete_domain', 'Delete Domain'), ('verify_domain', 'Verify Domain'), ('create_mailbox', 'Create Mailbox'), ('delete_mailbox', 'Delete Mailbox'), ('update_mailbox', 'Update Mailbox'), ('create_alias', 'Create Alias'), ('delete_alias', 'Delete Alias')], help_text='Type of provisioning task', max_length=30)),
                ('target_id', models.CharField(help_text='ID of the object being provisioned', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', help_text='Current task status', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Task result or error message')),
                ('payload', models.JSONField(blank=True, help_text='Additional task data', null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_provisioning_tasks', to='core.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_part', models.CharField(help_text='Username part before @', max_length=64)),
                ('password_hash', models.CharField(help_text='Hashed password for authentication', max_length=128)),
                ('is_active', models.BooleanField(default=True, help_text='Whether mailbox is active')),
                ('quota_mb', models.PositiveIntegerField(default=1024, help_text='Storage quota in megabytes')),
                ('last_login', models.DateTimeField(blank=True, help_text='Last successful login timestamp', null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailboxes', to='email_hosting.emaildomain')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailboxes', to='core.site')),
                ('user', models.ForeignKey(blank=True, help_text='Associated user account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailboxes', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailboxes', to='core.workspace')),
            ],
            options={
                'ordering': ['local_part'],
                'unique_together': {('domain', 'local_part')},
            },
        ),
        migrations.CreateModel(
            name='MailAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_address', models.EmailField(help_text='Source email address for alias', max_length=254)),
                ('active', models.BooleanField(default=True, help_text='Whether alias is active')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_aliases', to='core.site')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_aliases', to='core.workspace')),
                ('destination_mailbox', models.ForeignKey(help_text='Mailbox to forward emails to', on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='email_hosting.mailbox')),
            ],
            options={
                'ordering': ['source_address'],
                'unique_together': {('source_address', 'destination_mailbox')},
            },
        ),
    ]
