# Generated by Django 6.0.3 on 2026-03-10 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_cart_order_productcategory_product_productvariant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('hero', 'Hero'), ('feature', 'Feature'), ('cta', 'Call to Action'), ('testimonial', 'Testimonial'), ('pricing', 'Pricing'), ('faq', 'FAQ'), ('footer', 'Footer'), ('header', 'Header'), ('content', 'Content'), ('gallery', 'Gallery'), ('form', 'Form'), ('other', 'Other')], default='other', max_length=40)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('builder_data', models.JSONField(blank=True, default=dict)),
                ('html', models.TextField(blank=True)),
                ('css', models.TextField(blank=True)),
                ('is_global', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('usage_count', models.IntegerField(default=0)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_templates', to='builder.site')),
            ],
            options={
                'ordering': ['-is_global', '-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain_name', models.CharField(max_length=255, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('failed', 'Verification Failed')], default='pending', max_length=20)),
                ('verification_token', models.CharField(blank=True, max_length=100)),
                ('verification_method', models.CharField(blank=True, max_length=40)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('ssl_enabled', models.BooleanField(default=False)),
                ('dns_records', models.JSONField(blank=True, default=list)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='builder.site')),
            ],
            options={
                'ordering': ['-is_primary', 'domain_name'],
            },
        ),
        migrations.CreateModel(
            name='MediaFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('path', models.CharField(max_length=500)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='builder.mediafolder')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_folders', to='builder.site')),
            ],
            options={
                'ordering': ['path', 'name'],
            },
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='builder.mediafolder'),
        ),
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=160)),
                ('location', models.CharField(default='header', max_length=60)),
                ('items', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigation_menus', to='builder.site')),
            ],
            options={
                'ordering': ['location', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SEOAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('average_position', models.FloatField(default=0.0)),
                ('ctr', models.FloatField(default=0.0)),
                ('source', models.CharField(default='google_search_console', max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo_analytics', to='builder.page')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_analytics', to='builder.site')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='URLRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_path', models.CharField(max_length=500)),
                ('target_path', models.CharField(max_length=500)),
                ('redirect_type', models.CharField(choices=[('301', '301 Permanent'), ('302', '302 Temporary')], default='301', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('hit_count', models.IntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirects', to='builder.site')),
            ],
            options={
                'ordering': ['site', 'source_path'],
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('url', models.URLField(max_length=500)),
                ('event', models.CharField(choices=[('page.published', 'Page Published'), ('post.published', 'Post Published'), ('product.published', 'Product Published'), ('order.created', 'Order Created'), ('form.submitted', 'Form Submitted')], max_length=60)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('secret', models.CharField(blank=True, max_length=100)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('success_count', models.IntegerField(default=0)),
                ('failure_count', models.IntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='builder.site')),
            ],
            options={
                'ordering': ['event', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='mediafolder',
            constraint=models.UniqueConstraint(fields=('site', 'path'), name='unique_site_folder_path'),
        ),
        migrations.AddConstraint(
            model_name='navigationmenu',
            constraint=models.UniqueConstraint(fields=('site', 'slug'), name='unique_site_menu_slug'),
        ),
        migrations.AddConstraint(
            model_name='seoanalytics',
            constraint=models.UniqueConstraint(fields=('site', 'page', 'date', 'source'), name='unique_seo_analytics_entry'),
        ),
        migrations.AddConstraint(
            model_name='urlredirect',
            constraint=models.UniqueConstraint(fields=('site', 'source_path'), name='unique_site_redirect_source'),
        ),
    ]
