# Generated by Django 6.0.3 on 2026-03-10 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_blocktemplate_domain_mediafolder_mediaasset_folder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotsTxt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(default='User-agent: *\nAllow: /')),
                ('is_custom', models.BooleanField(default=False)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='robots_txt', to='builder.site')),
            ],
            options={
                'verbose_name': 'Robots.txt',
                'verbose_name_plural': 'Robots.txt',
            },
        ),
    ]
