# Generated by Django 5.2.5 on 2026-03-10 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_robotstxt'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='auth_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='domain',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='last_verification_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='nameservers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='domain',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='privacy_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='domain',
            name='registered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='registrar',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='domain',
            name='registrar_account',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='domain',
            name='registration_status',
            field=models.CharField(choices=[('unregistered', 'Unregistered / External'), ('active', 'Active'), ('expired', 'Expired'), ('pending_transfer', 'Pending Transfer'), ('pending_delete', 'Pending Delete'), ('locked', 'Locked')], default='unregistered', max_length=30),
        ),
        migrations.AddField(
            model_name='domain',
            name='ssl_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='domain',
            name='transfer_lock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='verification_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='whois_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='domain',
            name='whois_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='verification_method',
            field=models.CharField(blank=True, choices=[('dns_txt', 'DNS TXT Record'), ('file', 'File Upload')], default='dns_txt', max_length=40),
        ),
        migrations.CreateModel(
            name='DomainAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255)),
                ('available', models.BooleanField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, default='USD', max_length=10)),
                ('registrar', models.CharField(blank=True, max_length=140)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['domain_name', 'checked_at'], name='builder_dom_domain__8c70c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='DomainContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('registrant', 'Registrant'), ('admin', 'Administrative'), ('tech', 'Technical'), ('billing', 'Billing')], default='registrant', max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('organization', models.CharField(blank=True, max_length=140)),
                ('address1', models.CharField(blank=True, max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code', max_length=2)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_contacts', to='builder.site')),
            ],
            options={
                'ordering': ['role', 'last_name'],
            },
        ),
        migrations.AddField(
            model_name='domain',
            name='registrant_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domains_as_registrant', to='builder.domaincontact'),
        ),
    ]
