# Generated by Django 5.2.5 on 2026-03-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0006_domain_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocktemplate',
            name='author',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='blocktemplate',
            name='plan_required',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='blocktemplate',
            name='preview_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='blocktemplate',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('marketplace', 'Marketplace'), ('disabled', 'Disabled')], default='published', max_length=20),
        ),
        migrations.AddField(
            model_name='blocktemplate',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
