# Generated by Django 5.2.5 on 2026-03-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0009_job_workspace_site_workspace_workspaceinvitation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='Schedule publish time', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='Schedule publish time', null=True),
        ),
    ]
