# Generated by Django 5.2.5 on 2026-03-11 18:58

import django.db.models.deletion
from django.db import migrations, models


def seed_default_locales(apps, schema_editor):
    Site = apps.get_model("builder", "Site")
    SiteLocale = apps.get_model("builder", "SiteLocale")

    for site in Site.objects.all():
        settings = site.settings or {}
        localization = settings.get("localization") or {}
        default_locale = (localization.get("default_locale") or "en").replace("_", "-")
        normalized_code = "-".join(
            [
                part.lower() if index == 0 else (part.upper() if len(part) == 2 and part.isalpha() else part.title() if len(part) == 4 and part.isalpha() else part.lower())
                for index, part in enumerate(part for part in default_locale.split("-") if part)
            ]
        ) or "en"
        language = normalized_code.split("-", 1)[0]
        direction = "rtl" if language in {"ar", "fa", "he", "ku", "ps", "sd", "ug", "ur"} else "ltr"
        SiteLocale.objects.get_or_create(
            site=site,
            code=normalized_code,
            defaults={
                "direction": direction,
                "is_default": True,
                "is_enabled": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0010_page_scheduled_at_post_scheduled_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLocale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32)),
                ('direction', models.CharField(choices=[('ltr', 'Left to right'), ('rtl', 'Right to left')], default='ltr', max_length=3)),
                ('is_default', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locales', to='builder.site')),
            ],
            options={
                'ordering': ['-is_default', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=180)),
                ('path', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('seo', models.JSONField(blank=True, default=dict)),
                ('page_settings', models.JSONField(blank=True, default=dict)),
                ('builder_data', models.JSONField(blank=True, default=dict)),
                ('html', models.TextField(blank=True)),
                ('css', models.TextField(blank=True)),
                ('js', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='builder.page')),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_translations', to='builder.sitelocale')),
            ],
            options={
                'ordering': ['locale__code', 'title'],
            },
        ),
        migrations.AddConstraint(
            model_name='sitelocale',
            constraint=models.UniqueConstraint(fields=('site', 'code'), name='unique_site_locale_code'),
        ),
        migrations.AddConstraint(
            model_name='sitelocale',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('site',), name='unique_default_locale_per_site'),
        ),
        migrations.AddConstraint(
            model_name='pagetranslation',
            constraint=models.UniqueConstraint(fields=('page', 'locale'), name='unique_page_locale_translation'),
        ),
        migrations.AddConstraint(
            model_name='pagetranslation',
            constraint=models.UniqueConstraint(fields=('locale', 'path'), name='unique_locale_translation_path'),
        ),
        migrations.RunPython(seed_default_locales, migrations.RunPython.noop),
    ]
