# Generated by Django 5.2.5 on 2026-03-11 19:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0011_sitelocale_pagetranslation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('key', models.SlugField(max_length=80)),
                ('hypothesis', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('coverage_percent', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('goal_form_name', models.CharField(blank=True, max_length=140)),
                ('audience', models.JSONField(blank=True, default=dict)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('locale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='builder.sitelocale')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='builder.page')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_experiments', to='builder.site')),
            ],
            options={
                'ordering': ['page__title', '-updated_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PageExperimentVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('key', models.SlugField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=280)),
                ('is_control', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('weight', models.PositiveIntegerField(default=50)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('seo', models.JSONField(blank=True, default=dict)),
                ('page_settings', models.JSONField(blank=True, default=dict)),
                ('builder_data', models.JSONField(blank=True, default=dict)),
                ('html', models.TextField(blank=True)),
                ('css', models.TextField(blank=True)),
                ('js', models.TextField(blank=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='builder.pageexperiment')),
            ],
            options={
                'ordering': ['-is_control', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExperimentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale_code', models.CharField(blank=True, max_length=32)),
                ('visitor_id', models.CharField(max_length=64)),
                ('event_type', models.CharField(choices=[('exposure', 'Exposure'), ('conversion', 'Conversion')], max_length=20)),
                ('goal_key', models.CharField(blank=True, max_length=140)),
                ('request_path', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiment_events', to='builder.page')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_events', to='builder.site')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='builder.pageexperiment')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='builder.pageexperimentvariant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pageexperiment',
            index=models.Index(fields=['site', 'page', 'status'], name='builder_pag_site_id_aa280a_idx'),
        ),
        migrations.AddIndex(
            model_name='pageexperiment',
            index=models.Index(fields=['page', 'locale', 'status'], name='builder_pag_page_id_e01531_idx'),
        ),
        migrations.AddConstraint(
            model_name='pageexperiment',
            constraint=models.UniqueConstraint(fields=('site', 'key'), name='unique_site_page_experiment_key'),
        ),
        migrations.AddConstraint(
            model_name='pageexperimentvariant',
            constraint=models.UniqueConstraint(fields=('experiment', 'key'), name='unique_experiment_variant_key'),
        ),
        migrations.AddIndex(
            model_name='experimentevent',
            index=models.Index(fields=['site', 'page', 'event_type'], name='builder_exp_site_id_52056c_idx'),
        ),
        migrations.AddIndex(
            model_name='experimentevent',
            index=models.Index(fields=['experiment', 'event_type', 'created_at'], name='builder_exp_experim_9b9ac3_idx'),
        ),
        migrations.AddIndex(
            model_name='experimentevent',
            index=models.Index(fields=['visitor_id', 'event_type'], name='builder_exp_visitor_c50cd0_idx'),
        ),
        migrations.AddConstraint(
            model_name='experimentevent',
            constraint=models.UniqueConstraint(fields=('experiment', 'visitor_id', 'event_type', 'goal_key'), name='unique_experiment_event_per_goal'),
        ),
    ]
