# Generated by Django 5.2.5 on 2026-03-11 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0012_pageexperiment_pageexperimentvariant_experimentevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('changes_requested', 'Changes requested'), ('approved', 'Approved')], default='draft', max_length=24)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('last_note', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_page_reviews', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_page_reviews', to=settings.AUTH_USER_MODEL)),
                ('locale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_reviews', to='builder.sitelocale')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='builder.page')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_page_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['page__title', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PageReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('mentions', models.JSONField(blank=True, default=list)),
                ('anchor', models.JSONField(blank=True, default=dict)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_review_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='builder.pagereviewcomment')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_page_review_comments', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='builder.pagereview')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pagereview',
            index=models.Index(fields=['page', 'status'], name='builder_pag_page_id_8cb33f_idx'),
        ),
        migrations.AddIndex(
            model_name='pagereview',
            index=models.Index(fields=['assigned_to', 'status'], name='builder_pag_assigne_c53a99_idx'),
        ),
        migrations.AddConstraint(
            model_name='pagereview',
            constraint=models.UniqueConstraint(fields=('page', 'locale'), name='unique_page_review_per_locale'),
        ),
        migrations.AddConstraint(
            model_name='pagereview',
            constraint=models.UniqueConstraint(condition=models.Q(('locale__isnull', True)), fields=('page',), name='unique_default_page_review'),
        ),
        migrations.AddIndex(
            model_name='pagereviewcomment',
            index=models.Index(fields=['review', 'is_resolved'], name='builder_pag_review__8cefcc_idx'),
        ),
        migrations.AddIndex(
            model_name='pagereviewcomment',
            index=models.Index(fields=['author', 'created_at'], name='builder_pag_author__5cf0ae_idx'),
        ),
    ]
