# Generated by Django 6.0.3 on 2026-03-12 13:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0014_order_pricing_details_shippingzone_shippingrate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('headline', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('offer_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed amount'), ('trial_extension', 'Trial extension'), ('seat_bonus', 'Seat bonus'), ('custom', 'Custom')], default='percentage', max_length=24)),
                ('target_plan', models.CharField(choices=[('all', 'All plans'), ('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='all', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('duration_in_months', models.PositiveIntegerField(default=1)),
                ('seats_delta', models.IntegerField(default=0)),
                ('cta_url', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_platform_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlatformEmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('subject', models.CharField(max_length=220)),
                ('preview_text', models.CharField(blank=True, max_length=255)),
                ('body_text', models.TextField()),
                ('body_html', models.TextField(blank=True)),
                ('audience_type', models.CharField(choices=[('all_users', 'All users'), ('workspace_owners', 'Workspace owners'), ('active_subscribers', 'Active subscribers'), ('trialing', 'Trialing'), ('inactive_subscribers', 'Inactive subscribers')], default='all_users', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_platform_email_campaigns', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_campaigns', to='builder.platformoffer')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise'), ('custom', 'Custom')], default='starter', max_length=20)),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='trialing', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Custom')], default='monthly', max_length=20)),
                ('seats', models.PositiveIntegerField(default=1)),
                ('monthly_recurring_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('external_customer_id', models.CharField(blank=True, max_length=120)),
                ('external_subscription_id', models.CharField(blank=True, max_length=120)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_ends_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_subscription', to='builder.workspace')),
            ],
            options={
                'ordering': ['workspace__name'],
            },
        ),
    ]
