# Generated by Django 5.2.5 on 2026-04-03

from django.db import migrations, models


def _backfill_revision_schema_version(apps, schema_editor):
    PageRevision = apps.get_model("builder", "PageRevision")

    for revision in PageRevision.objects.all().iterator():
        snapshot = revision.snapshot if isinstance(revision.snapshot, dict) else {}
        value = snapshot.get("schema_version")
        try:
            parsed = int(value)
        except (TypeError, ValueError):
            parsed = 1
        if parsed <= 0:
            parsed = 1
        revision.builder_schema_version = parsed
        revision.save(update_fields=["builder_schema_version"])


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0015_platformoffer_platformemailcampaign_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagerevision",
            name="builder_schema_version",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.RunPython(_backfill_revision_schema_version, migrations.RunPython.noop),
    ]
