# Generated by Django 5.2.5 on 2026-04-20 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rbacpermission_rbacrole_personalapikey_last_used_ip_and_more"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhook",
            name="event",
            field=models.CharField(
                choices=[
                    ("page.published", "Page Published"),
                    ("site.published", "Site Published"),
                    ("post.published", "Post Published"),
                    ("product.published", "Product Published"),
                    ("order.created", "Order Created"),
                    ("customer.created", "Customer Created"),
                    ("form.submitted", "Form Submitted"),
                    ("ai.job.completed", "AI Job Completed"),
                    ("ai.job.failed", "AI Job Failed"),
                    ("publish.job.completed", "Publish Job Completed"),
                ],
                max_length=60,
            ),
        ),
        migrations.CreateModel(
            name="AutomationWebhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=140)),
                ("url", models.URLField(max_length=500)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("site.published", "Site Published"),
                            ("post.published", "Post Published"),
                            ("order.created", "Order Created"),
                            ("customer.created", "Customer Created"),
                            ("form.submitted", "Form Submitted"),
                            ("ai.job.completed", "AI Job Completed"),
                            ("publish.job.completed", "Publish Job Completed"),
                        ],
                        max_length=80,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("secret", models.CharField(blank=True, max_length=120)),
                ("headers", models.JSONField(blank=True, default=dict)),
                ("timeout_seconds", models.PositiveIntegerField(default=15)),
                ("max_attempts", models.PositiveIntegerField(default=5)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_webhooks",
                        to="core.site",
                    ),
                ),
            ],
            options={
                "db_table": "automation_webhooks",
                "ordering": ["event", "name"],
            },
        ),
        migrations.CreateModel(
            name="AutomationWebhookDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event", models.CharField(max_length=80)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=5)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("response_status", models.IntegerField(blank=True, null=True)),
                ("response_body", models.TextField(blank=True)),
                ("response_time_ms", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="notifications.automationwebhook",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="automationwebhook",
            constraint=models.UniqueConstraint(
                fields=("site", "name", "event"),
                name="notifications_unique_automation_webhook",
            ),
        ),
        migrations.AddIndex(
            model_name="automationwebhookdelivery",
            index=models.Index(
                fields=["status", "next_attempt_at"],
                name="notificatio_status_7643d3_idx",
            ),
        ),
    ]
